function feedforward = FFdf(theta)
%FFdf
%    FEEDFORWARD = FFdf(THETA)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    2025-12-06 00:55:24

feedforward = (6.37e+2./1.0e+1)./cos(theta);
end
