function joint_pos = LegIKine
%LegIKine
%    JOINT_POS = LegIKine

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    2025-12-25 14:28:26

t2 = NaN;
joint_pos = [t2;t2];
end
